// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLtDsYzDPW1NvO3bYASip9C5GEnt8iR2U',
    appId: '1:632217680205:web:32697c942cd24cb4aa9f04',
    messagingSenderId: '632217680205',
    projectId: 'elif-chat',
    authDomain: 'elif-chat.firebaseapp.com',
    storageBucket: 'elif-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIdEqVBgRbYikIEGpFLiDA2lv4PoiJa-s',
    appId: '1:632217680205:android:94967ac5b9a96c82aa9f04',
    messagingSenderId: '632217680205',
    projectId: 'elif-chat',
    storageBucket: 'elif-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xljloveQyM4ZUhTP-7Smhov-zSV6lrY',
    appId: '1:632217680205:ios:a80d01df5be68a27aa9f04',
    messagingSenderId: '632217680205',
    projectId: 'elif-chat',
    storageBucket: 'elif-chat.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
